#!/usr/bin/env python
# -*- coding: utf8 -*-
# ted-json2html.py - Converts the JSON generated by ted-scrape.py into HTML.
# Copyright (C) 2012 Gabriel Rodríguez Alberich <chewie@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import datetime

view_url_p = "http://ted.com/talks/view/id/%(video_id)s"
download_url_p = "http://download.ted.com/talks/%(video_name)s-480p.mp4" \
                 "?apikey=TEDDOWNLOAD"


def td(text):
    return """<td>%s</td>""" % text


def main():

    with open("ted-scrape.json") as f:
        talks = json.load(f)

    print u"""
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
    <html> 
    	<head> 
    		<meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
            <title>TED Talks on a Table</title> 
    		<style type="text/css" title="currentStyle"> 
    			@import "css/demo_page.css";
    			@import "css/demo_table.css";
    		</style>
            <script type="text/javascript" language="javascript" src="js/jquery.js"></script> 
            <script type="text/javascript" language="javascript" src="js/jquery.dataTables.min.js"></script> 
            <script type="text/javascript" charset="utf-8"> 
    	        $(document).ready(function() {
                            $('span.searchable')
                             .click(function () {
                               $('#tedtable_filter input').val($(this).text());
                               $('#tedtable_filter input').trigger(jQuery.Event("keyup"));
                             });

    		        $('#tedtable').dataTable( {
                                "sPaginationType": "full_numbers",
                                "iDisplayLength": 25,
                                "bLengthChange": false,
                                "aaSorting": [[5,'desc']]
                            } );
    	        } );
            </script> 
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37868276-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
    </head>
    <body id="dt_example">
    <div id="container">
    <h1 id="title" class="full_width">TED Talks on a Table</h1>
    <p>A quick way to look for interesting TED talks. These are all %d TED videos available on <a href="http://ted.com">ted.com</a> (as of %s) on a sortable, searchable table. Use the search box below to filter them by any of the provided columns. You can use oxplot's wonderful <a href="https://github.com/oxplot/ted2mkv">ted2mkv</a> to download a video and convert it to an MKV file with embedded metadata, including all available subtitles.</p>

    <table cellpadding="0" cellspacing="0" border="0" class="display" id="tedtable">
      <thead> 
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Download link</th>
          <th>Available subtitles</th>
          <th>Summary</th>
          <th>Filming date</th>
          <th>Tags</th>
          <th>Event</th>
        </tr>
      </thead>
      <tbody>""" % (len(talks), datetime.datetime.now().strftime("%b %d, %Y"))

    n = 0
    for talk in talks:
        print u"""<tr class="%s">""" % (n % 2 == 0 and "even" or "odd")
        if talk['title'].startswith(talk['author'] + ":"):
            talk['title'] = talk['title'][len(talk['author']) + 2:].strip()
        print td('<span class="big"><a href="%s">%s</a></span>' % (
            view_url_p %
            talk,
            talk['title'].encode('utf8'))
            )
        print td('<span class="searchable">%s</span>' %
                 talk['author'].encode("utf8"))
        print td(u"""<a href="%s">Download</a>""" % download_url_p % talk)
        print td('<span class="small">' + ', '.join(talk.get('lang_codes', []))
                 + "</span>")
        print td(talk.get('summary', '').encode("utf8"))

        if 'filmed_date' in talk:
            date = datetime.datetime.strptime(talk['filmed_date'],
              '%Y-%m-%dT%H:%M:%S').strftime("%b %Y")
            print td(date)
        else:
            print td("")

        if 'tags' in talk:
            tags = u", ".join(['<span class="searchable">%s</span>' %
                               tag for tag in talk['tags']])
        else:
            tags = u""
        print td('<span class="small">' + tags + "</span>")

        print td(talk.get('event', '').encode("utf8"))

        print u"""</tr>"""
        n += 1

    print u"""</tbody>
      <tfoot>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Download link</th>
          <th>Available subtitles</th>
          <th>Summary</th>
          <th>Filming date</th>
          <th>Tags</th>
          <th>Event</th>
        </tr>
      </tfoot>
    </table>
    <div class="spacer"></div>
    <div id="footer" class="clear" style="text-align:center;">
    Compiled and maintained by <a href="http://twitter.com/vibragiel">Gabriel Rodríguez</a> (<a href="mailto:chewie@gmail.com">chewie@gmail.com</a>).<br>
    This website is not affiliated in any way with TED. All videos and associated content are &copy; TED Conferences, LLC, available under a <a href="http://creativecommons.org/licenses/by-nc-nd/3.0/">CC by-nc-sa</a> license.
    </div>
    </div>
    </body>
    </html>
    """.encode("utf8")


if __name__ == '__main__':
    main()
